version: "3.8"
services:
  frontend:
    build: app
    x-aws-pull_credentials: arn:aws:secretsmanager:us-west-2:175142243308:secret:DockerHubAccessToken-8cRLae
    image: metcalfc/timestamper
    ports:
      - "5000:5000"
    depends_on:
      - backend
  backend:
    image: redis:alpine
